### ISSUE TITLE
Uncoverable lines are not sent in the report at all

### ISSUE THREAD

**Issue by perlpunk** [houseabsolute/Devel-Cover-Report-Codecovbash#1]
We found that our Coverage reports on codecov.io are sometimes off by 1 or more lines. It starts at lines with `# uncoverable statement`.
We are using version 0.03

The Devel::Cover HTML report looks fine, but in the codecov.io HTML, the green/red markers move up, so that empty lines are marked as green for example:
https://codecov.io/gh/os-autoinst/openQA/src/master/t/lib/OpenQA/Test/Utils.pm#L652

I looked into the code and found that this is done on purpose:
https://github.com/houseabsolute/Devel-Cover-Report-Codecovbash/blob/master/lib/Devel/Cover/Report/Codecovbash.pm#L93
```
return if $statement->[0]->uncoverable;
```

But maybe what was wanted is:
```
return undef if $statement->[0]->uncoverable;
```
Because `return` in list context will just return an empty list, so nothing is pushed into the array at all.

**Comment by autarch** [comment]
Thanks for the report.

If you look at the source for this module, you'll see that I just copied this from Devel-Cover-Report-Codecov. I don't actually know what most of this does! I'm happy to accept a patch, but maybe you'd like to take this distro over if you're actually using it. I only created it to test out codecov support for [my Azure Pipelines helpers project](https://github.com/houseabsolute/ci-perl-helpers).

**Comment by perlpunk** [comment]
Thanks, I would take the module over :)
My CPAN handle: TINITA

**Comment by autarch** [comment]
You are now the primary owner. We can also transfer this repo to another owner. I think the easiest way to do that is to add you as an owner of this repo and let you transfer it. Otherwise you'd need to give me admin access to an organization of your choice.

**Comment by perlpunk** [comment]
Great, thanks.
From my experience, it's enough if I fork it (which I just did), and as soon as you delete your repo (after I made a new release), my fork will be seen as the origin.

**Comment by autarch** [comment]
Alright, sounds good. I will delete the repo now.
